import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthProvider from "@/Context/AuthProvider";
import './globals.css' 
import { Toaster } from "@/components/ui/sonner" // imp to include in layout


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-blue-900 text-white`} >
        <Toaster/>
        {children}
             </body>
         </AuthProvider>
    </html>
  );
}
